/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using YL.Web.Api.ThirdParty.Loan.Client.Client;
using YL.Web.Api.ThirdParty.Loan.Client.Model;

namespace YL.Web.Api.ThirdParty.Loan.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoansApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get all loans associated with your Customer ID
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET Loans/1cd09db1-e6d2-4d64-aeba-9e64b818461a/loans
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>List&lt;LoansModel&gt;</returns>
        List<LoansModel> GetAllLoans (string customerId, string apiVersion = default(string));

        /// <summary>
        /// Get all loans associated with your Customer ID
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET Loans/1cd09db1-e6d2-4d64-aeba-9e64b818461a/loans
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>ApiResponse of List&lt;LoansModel&gt;</returns>
        ApiResponse<List<LoansModel>> GetAllLoansWithHttpInfo (string customerId, string apiVersion = default(string));
        /// <summary>
        /// Get a specific loan by its Loan ID
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>List&lt;LoanModel&gt;</returns>
        List<LoanModel> GetLoan (string loanId, string apiVersion = default(string));

        /// <summary>
        /// Get a specific loan by its Loan ID
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>ApiResponse of List&lt;LoanModel&gt;</returns>
        ApiResponse<List<LoanModel>> GetLoanWithHttpInfo (string loanId, string apiVersion = default(string));
        /// <summary>
        /// Get the repayment information associated with a given loan&#39;s Loan ID
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee/repayments
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>LoanRepaymentModel</returns>
        LoanRepaymentModel GetRepayments (string loanId, string apiVersion = default(string));

        /// <summary>
        /// Get the repayment information associated with a given loan&#39;s Loan ID
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee/repayments
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>ApiResponse of LoanRepaymentModel</returns>
        ApiResponse<LoanRepaymentModel> GetRepaymentsWithHttpInfo (string loanId, string apiVersion = default(string));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoansApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get all loans associated with your Customer ID
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET Loans/1cd09db1-e6d2-4d64-aeba-9e64b818461a/loans
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of List&lt;LoansModel&gt;</returns>
        System.Threading.Tasks.Task<List<LoansModel>> GetAllLoansAsync (string customerId, string apiVersion = default(string));

        /// <summary>
        /// Get all loans associated with your Customer ID
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET Loans/1cd09db1-e6d2-4d64-aeba-9e64b818461a/loans
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;LoansModel&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<LoansModel>>> GetAllLoansAsyncWithHttpInfo (string customerId, string apiVersion = default(string));
        /// <summary>
        /// Get a specific loan by its Loan ID
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of List&lt;LoanModel&gt;</returns>
        System.Threading.Tasks.Task<List<LoanModel>> GetLoanAsync (string loanId, string apiVersion = default(string));

        /// <summary>
        /// Get a specific loan by its Loan ID
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;LoanModel&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<LoanModel>>> GetLoanAsyncWithHttpInfo (string loanId, string apiVersion = default(string));
        /// <summary>
        /// Get the repayment information associated with a given loan&#39;s Loan ID
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee/repayments
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of LoanRepaymentModel</returns>
        System.Threading.Tasks.Task<LoanRepaymentModel> GetRepaymentsAsync (string loanId, string apiVersion = default(string));

        /// <summary>
        /// Get the repayment information associated with a given loan&#39;s Loan ID
        /// </summary>
        /// <remarks>
        /// Sample request:                    GET /Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee/repayments
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of ApiResponse (LoanRepaymentModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<LoanRepaymentModel>> GetRepaymentsAsyncWithHttpInfo (string loanId, string apiVersion = default(string));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoansApi : ILoansApiSync, ILoansApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LoansApi : ILoansApi
    {
        private YL.Web.Api.ThirdParty.Loan.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LoansApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LoansApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoansApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LoansApi(String basePath)
        {
            this.Configuration = YL.Web.Api.ThirdParty.Loan.Client.Client.Configuration.MergeConfigurations(
                YL.Web.Api.ThirdParty.Loan.Client.Client.GlobalConfiguration.Instance,
                new YL.Web.Api.ThirdParty.Loan.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new YL.Web.Api.ThirdParty.Loan.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new YL.Web.Api.ThirdParty.Loan.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = YL.Web.Api.ThirdParty.Loan.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoansApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LoansApi(YL.Web.Api.ThirdParty.Loan.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = YL.Web.Api.ThirdParty.Loan.Client.Client.Configuration.MergeConfigurations(
                YL.Web.Api.ThirdParty.Loan.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new YL.Web.Api.ThirdParty.Loan.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new YL.Web.Api.ThirdParty.Loan.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = YL.Web.Api.ThirdParty.Loan.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoansApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public LoansApi(YL.Web.Api.ThirdParty.Loan.Client.Client.ISynchronousClient client,YL.Web.Api.ThirdParty.Loan.Client.Client.IAsynchronousClient asyncClient, YL.Web.Api.ThirdParty.Loan.Client.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = YL.Web.Api.ThirdParty.Loan.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public YL.Web.Api.ThirdParty.Loan.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public YL.Web.Api.ThirdParty.Loan.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public YL.Web.Api.ThirdParty.Loan.Client.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public YL.Web.Api.ThirdParty.Loan.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get all loans associated with your Customer ID Sample request:                    GET Loans/1cd09db1-e6d2-4d64-aeba-9e64b818461a/loans
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>List&lt;LoansModel&gt;</returns>
        public List<LoansModel> GetAllLoans (string customerId, string apiVersion = default(string))
        {
             YL.Web.Api.ThirdParty.Loan.Client.Client.ApiResponse<List<LoansModel>> localVarResponse = GetAllLoansWithHttpInfo(customerId, apiVersion);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get all loans associated with your Customer ID Sample request:                    GET Loans/1cd09db1-e6d2-4d64-aeba-9e64b818461a/loans
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>ApiResponse of List&lt;LoansModel&gt;</returns>
        public YL.Web.Api.ThirdParty.Loan.Client.Client.ApiResponse< List<LoansModel> > GetAllLoansWithHttpInfo (string customerId, string apiVersion = default(string))
        {
            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException(400, "Missing required parameter 'customerId' when calling LoansApi->GetAllLoans");

            YL.Web.Api.ThirdParty.Loan.Client.Client.RequestOptions localVarRequestOptions = new YL.Web.Api.ThirdParty.Loan.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (customerId != null)
                localVarRequestOptions.PathParameters.Add("customerId", YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.ParameterToString(customerId)); // path parameter
            if (apiVersion != null)
                localVarRequestOptions.HeaderParameters.Add("api-version", YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.ParameterToString(apiVersion)); // header parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< List<LoansModel> >("/Loans/{customerId}/loans", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllLoans", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get all loans associated with your Customer ID Sample request:                    GET Loans/1cd09db1-e6d2-4d64-aeba-9e64b818461a/loans
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of List&lt;LoansModel&gt;</returns>
        public async System.Threading.Tasks.Task<List<LoansModel>> GetAllLoansAsync (string customerId, string apiVersion = default(string))
        {
             YL.Web.Api.ThirdParty.Loan.Client.Client.ApiResponse<List<LoansModel>> localVarResponse = await GetAllLoansAsyncWithHttpInfo(customerId, apiVersion);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get all loans associated with your Customer ID Sample request:                    GET Loans/1cd09db1-e6d2-4d64-aeba-9e64b818461a/loans
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="customerId">Customer ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;LoansModel&gt;)</returns>
        public async System.Threading.Tasks.Task<YL.Web.Api.ThirdParty.Loan.Client.Client.ApiResponse<List<LoansModel>>> GetAllLoansAsyncWithHttpInfo (string customerId, string apiVersion = default(string))
        {
            // verify the required parameter 'customerId' is set
            if (customerId == null)
                throw new YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException(400, "Missing required parameter 'customerId' when calling LoansApi->GetAllLoans");


            YL.Web.Api.ThirdParty.Loan.Client.Client.RequestOptions localVarRequestOptions = new YL.Web.Api.ThirdParty.Loan.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (customerId != null)
                localVarRequestOptions.PathParameters.Add("customerId", YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.ParameterToString(customerId)); // path parameter
            if (apiVersion != null)
                localVarRequestOptions.HeaderParameters.Add("api-version", YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.ParameterToString(apiVersion)); // header parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<LoansModel>>("/Loans/{customerId}/loans", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllLoans", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a specific loan by its Loan ID Sample request:                    GET Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>List&lt;LoanModel&gt;</returns>
        public List<LoanModel> GetLoan (string loanId, string apiVersion = default(string))
        {
             YL.Web.Api.ThirdParty.Loan.Client.Client.ApiResponse<List<LoanModel>> localVarResponse = GetLoanWithHttpInfo(loanId, apiVersion);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a specific loan by its Loan ID Sample request:                    GET Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>ApiResponse of List&lt;LoanModel&gt;</returns>
        public YL.Web.Api.ThirdParty.Loan.Client.Client.ApiResponse< List<LoanModel> > GetLoanWithHttpInfo (string loanId, string apiVersion = default(string))
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException(400, "Missing required parameter 'loanId' when calling LoansApi->GetLoan");

            YL.Web.Api.ThirdParty.Loan.Client.Client.RequestOptions localVarRequestOptions = new YL.Web.Api.ThirdParty.Loan.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (loanId != null)
                localVarRequestOptions.PathParameters.Add("loanId", YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.ParameterToString(loanId)); // path parameter
            if (apiVersion != null)
                localVarRequestOptions.HeaderParameters.Add("api-version", YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.ParameterToString(apiVersion)); // header parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< List<LoanModel> >("/Loans/{loanId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetLoan", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a specific loan by its Loan ID Sample request:                    GET Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of List&lt;LoanModel&gt;</returns>
        public async System.Threading.Tasks.Task<List<LoanModel>> GetLoanAsync (string loanId, string apiVersion = default(string))
        {
             YL.Web.Api.ThirdParty.Loan.Client.Client.ApiResponse<List<LoanModel>> localVarResponse = await GetLoanAsyncWithHttpInfo(loanId, apiVersion);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a specific loan by its Loan ID Sample request:                    GET Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;LoanModel&gt;)</returns>
        public async System.Threading.Tasks.Task<YL.Web.Api.ThirdParty.Loan.Client.Client.ApiResponse<List<LoanModel>>> GetLoanAsyncWithHttpInfo (string loanId, string apiVersion = default(string))
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException(400, "Missing required parameter 'loanId' when calling LoansApi->GetLoan");


            YL.Web.Api.ThirdParty.Loan.Client.Client.RequestOptions localVarRequestOptions = new YL.Web.Api.ThirdParty.Loan.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (loanId != null)
                localVarRequestOptions.PathParameters.Add("loanId", YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.ParameterToString(loanId)); // path parameter
            if (apiVersion != null)
                localVarRequestOptions.HeaderParameters.Add("api-version", YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.ParameterToString(apiVersion)); // header parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<LoanModel>>("/Loans/{loanId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetLoan", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get the repayment information associated with a given loan&#39;s Loan ID Sample request:                    GET /Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee/repayments
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>LoanRepaymentModel</returns>
        public LoanRepaymentModel GetRepayments (string loanId, string apiVersion = default(string))
        {
             YL.Web.Api.ThirdParty.Loan.Client.Client.ApiResponse<LoanRepaymentModel> localVarResponse = GetRepaymentsWithHttpInfo(loanId, apiVersion);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the repayment information associated with a given loan&#39;s Loan ID Sample request:                    GET /Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee/repayments
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>ApiResponse of LoanRepaymentModel</returns>
        public YL.Web.Api.ThirdParty.Loan.Client.Client.ApiResponse< LoanRepaymentModel > GetRepaymentsWithHttpInfo (string loanId, string apiVersion = default(string))
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException(400, "Missing required parameter 'loanId' when calling LoansApi->GetRepayments");

            YL.Web.Api.ThirdParty.Loan.Client.Client.RequestOptions localVarRequestOptions = new YL.Web.Api.ThirdParty.Loan.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (loanId != null)
                localVarRequestOptions.PathParameters.Add("loanId", YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.ParameterToString(loanId)); // path parameter
            if (apiVersion != null)
                localVarRequestOptions.HeaderParameters.Add("api-version", YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.ParameterToString(apiVersion)); // header parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< LoanRepaymentModel >("/Loans/{loanId}/repayments", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRepayments", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get the repayment information associated with a given loan&#39;s Loan ID Sample request:                    GET /Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee/repayments
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of LoanRepaymentModel</returns>
        public async System.Threading.Tasks.Task<LoanRepaymentModel> GetRepaymentsAsync (string loanId, string apiVersion = default(string))
        {
             YL.Web.Api.ThirdParty.Loan.Client.Client.ApiResponse<LoanRepaymentModel> localVarResponse = await GetRepaymentsAsyncWithHttpInfo(loanId, apiVersion);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the repayment information associated with a given loan&#39;s Loan ID Sample request:                    GET /Loans/71abf3e6-d6a8-45d2-8394-55cc32260bee/repayments
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="loanId">Loan ID (a string)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of ApiResponse (LoanRepaymentModel)</returns>
        public async System.Threading.Tasks.Task<YL.Web.Api.ThirdParty.Loan.Client.Client.ApiResponse<LoanRepaymentModel>> GetRepaymentsAsyncWithHttpInfo (string loanId, string apiVersion = default(string))
        {
            // verify the required parameter 'loanId' is set
            if (loanId == null)
                throw new YL.Web.Api.ThirdParty.Loan.Client.Client.ApiException(400, "Missing required parameter 'loanId' when calling LoansApi->GetRepayments");


            YL.Web.Api.ThirdParty.Loan.Client.Client.RequestOptions localVarRequestOptions = new YL.Web.Api.ThirdParty.Loan.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (loanId != null)
                localVarRequestOptions.PathParameters.Add("loanId", YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.ParameterToString(loanId)); // path parameter
            if (apiVersion != null)
                localVarRequestOptions.HeaderParameters.Add("api-version", YL.Web.Api.ThirdParty.Loan.Client.Client.ClientUtils.ParameterToString(apiVersion)); // header parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<LoanRepaymentModel>("/Loans/{loanId}/repayments", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRepayments", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
