/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using YL.Web.Api.ThirdParty.Loan.Client.Client;
using YL.Web.Api.ThirdParty.Loan.Client.Api;
using YL.Web.Api.ThirdParty.Loan.Client.Model;

namespace YL.Web.Api.ThirdParty.Loan.Client.Test
{
    /// <summary>
    ///  Class for testing LoansApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LoansApiTests : IDisposable
    {
        private LoansApi instance;

        public LoansApiTests()
        {
            instance = new LoansApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoansApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LoansApi
            //Assert.IsType(typeof(LoansApi), instance, "instance is a LoansApi");
        }

        
        /// <summary>
        /// Test GetAllLoans
        /// </summary>
        [Fact]
        public void GetAllLoansTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string customerId = null;
            //string apiVersion = null;
            //var response = instance.GetAllLoans(customerId, apiVersion);
            //Assert.IsType<List<LoansModel>> (response, "response is List<LoansModel>");
        }
        
        /// <summary>
        /// Test GetLoan
        /// </summary>
        [Fact]
        public void GetLoanTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string loanId = null;
            //string apiVersion = null;
            //var response = instance.GetLoan(loanId, apiVersion);
            //Assert.IsType<List<LoanModel>> (response, "response is List<LoanModel>");
        }
        
        /// <summary>
        /// Test GetRepayments
        /// </summary>
        [Fact]
        public void GetRepaymentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string loanId = null;
            //string apiVersion = null;
            //var response = instance.GetRepayments(loanId, apiVersion);
            //Assert.IsType<LoanRepaymentModel> (response, "response is LoanRepaymentModel");
        }
        
    }

}
