/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Loan.Client.Api;
using YL.Web.Api.ThirdParty.Loan.Client.Model;
using YL.Web.Api.ThirdParty.Loan.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Loan.Client.Test
{
    /// <summary>
    ///  Class for testing DefaultDetailsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DefaultDetailsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DefaultDetailsModel
        //private DefaultDetailsModel instance;

        public DefaultDetailsModelTests()
        {
            // TODO uncomment below to create an instance of DefaultDetailsModel
            //instance = new DefaultDetailsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DefaultDetailsModel
        /// </summary>
        [Fact]
        public void DefaultDetailsModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DefaultDetailsModel
            //Assert.IsInstanceOfType<DefaultDetailsModel> (instance, "variable 'instance' is a DefaultDetailsModel");
        }


        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'ReasonDetails'
        /// </summary>
        [Fact]
        public void ReasonDetailsTest()
        {
            // TODO unit test for the property 'ReasonDetails'
        }
        /// <summary>
        /// Test the property 'DateDefaulted'
        /// </summary>
        [Fact]
        public void DateDefaultedTest()
        {
            // TODO unit test for the property 'DateDefaulted'
        }
        /// <summary>
        /// Test the property 'CurrentAmountAtTimeOfDefault'
        /// </summary>
        [Fact]
        public void CurrentAmountAtTimeOfDefaultTest()
        {
            // TODO unit test for the property 'CurrentAmountAtTimeOfDefault'
        }

    }

}
