/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Loan.Client.Api;
using YL.Web.Api.ThirdParty.Loan.Client.Model;
using YL.Web.Api.ThirdParty.Loan.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Loan.Client.Test
{
    /// <summary>
    ///  Class for testing EarlyRenewalDetailsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EarlyRenewalDetailsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EarlyRenewalDetailsModel
        //private EarlyRenewalDetailsModel instance;

        public EarlyRenewalDetailsModelTests()
        {
            // TODO uncomment below to create an instance of EarlyRenewalDetailsModel
            //instance = new EarlyRenewalDetailsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EarlyRenewalDetailsModel
        /// </summary>
        [Fact]
        public void EarlyRenewalDetailsModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EarlyRenewalDetailsModel
            //Assert.IsInstanceOfType<EarlyRenewalDetailsModel> (instance, "variable 'instance' is a EarlyRenewalDetailsModel");
        }


        /// <summary>
        /// Test the property 'OldLoanId'
        /// </summary>
        [Fact]
        public void OldLoanIdTest()
        {
            // TODO unit test for the property 'OldLoanId'
        }
        /// <summary>
        /// Test the property 'OldLoanNumber'
        /// </summary>
        [Fact]
        public void OldLoanNumberTest()
        {
            // TODO unit test for the property 'OldLoanNumber'
        }
        /// <summary>
        /// Test the property 'IsOldLoanRepaid'
        /// </summary>
        [Fact]
        public void IsOldLoanRepaidTest()
        {
            // TODO unit test for the property 'IsOldLoanRepaid'
        }
        /// <summary>
        /// Test the property 'NewLoanId'
        /// </summary>
        [Fact]
        public void NewLoanIdTest()
        {
            // TODO unit test for the property 'NewLoanId'
        }
        /// <summary>
        /// Test the property 'NewLoanNumber'
        /// </summary>
        [Fact]
        public void NewLoanNumberTest()
        {
            // TODO unit test for the property 'NewLoanNumber'
        }

    }

}
