/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Loan.Client.Api;
using YL.Web.Api.ThirdParty.Loan.Client.Model;
using YL.Web.Api.ThirdParty.Loan.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Loan.Client.Test
{
    /// <summary>
    ///  Class for testing LoanFundingDetailsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoanFundingDetailsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoanFundingDetailsModel
        //private LoanFundingDetailsModel instance;

        public LoanFundingDetailsModelTests()
        {
            // TODO uncomment below to create an instance of LoanFundingDetailsModel
            //instance = new LoanFundingDetailsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoanFundingDetailsModel
        /// </summary>
        [Fact]
        public void LoanFundingDetailsModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanFundingDetailsModel
            //Assert.IsInstanceOfType<LoanFundingDetailsModel> (instance, "variable 'instance' is a LoanFundingDetailsModel");
        }


        /// <summary>
        /// Test the property 'FundingAmount'
        /// </summary>
        [Fact]
        public void FundingAmountTest()
        {
            // TODO unit test for the property 'FundingAmount'
        }
        /// <summary>
        /// Test the property 'FundingDate'
        /// </summary>
        [Fact]
        public void FundingDateTest()
        {
            // TODO unit test for the property 'FundingDate'
        }
        /// <summary>
        /// Test the property 'FundingPayments'
        /// </summary>
        [Fact]
        public void FundingPaymentsTest()
        {
            // TODO unit test for the property 'FundingPayments'
        }
        /// <summary>
        /// Test the property 'AmountFunded'
        /// </summary>
        [Fact]
        public void AmountFundedTest()
        {
            // TODO unit test for the property 'AmountFunded'
        }

    }

}
