/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Loan.Client.Api;
using YL.Web.Api.ThirdParty.Loan.Client.Model;
using YL.Web.Api.ThirdParty.Loan.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Loan.Client.Test
{
    /// <summary>
    ///  Class for testing LoanWriteOffDetailsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoanWriteOffDetailsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoanWriteOffDetailsModel
        //private LoanWriteOffDetailsModel instance;

        public LoanWriteOffDetailsModelTests()
        {
            // TODO uncomment below to create an instance of LoanWriteOffDetailsModel
            //instance = new LoanWriteOffDetailsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoanWriteOffDetailsModel
        /// </summary>
        [Fact]
        public void LoanWriteOffDetailsModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanWriteOffDetailsModel
            //Assert.IsInstanceOfType<LoanWriteOffDetailsModel> (instance, "variable 'instance' is a LoanWriteOffDetailsModel");
        }


        /// <summary>
        /// Test the property 'PaymentDate'
        /// </summary>
        [Fact]
        public void PaymentDateTest()
        {
            // TODO unit test for the property 'PaymentDate'
        }
        /// <summary>
        /// Test the property 'PaymentAmount'
        /// </summary>
        [Fact]
        public void PaymentAmountTest()
        {
            // TODO unit test for the property 'PaymentAmount'
        }

    }

}
