/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Loan.Client.Api;
using YL.Web.Api.ThirdParty.Loan.Client.Model;
using YL.Web.Api.ThirdParty.Loan.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Loan.Client.Test
{
    /// <summary>
    ///  Class for testing LoansModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoansModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoansModel
        //private LoansModel instance;

        public LoansModelTests()
        {
            // TODO uncomment below to create an instance of LoansModel
            //instance = new LoansModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoansModel
        /// </summary>
        [Fact]
        public void LoansModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoansModel
            //Assert.IsInstanceOfType<LoansModel> (instance, "variable 'instance' is a LoansModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LoanNumber'
        /// </summary>
        [Fact]
        public void LoanNumberTest()
        {
            // TODO unit test for the property 'LoanNumber'
        }
        /// <summary>
        /// Test the property 'LenderId'
        /// </summary>
        [Fact]
        public void LenderIdTest()
        {
            // TODO unit test for the property 'LenderId'
        }
        /// <summary>
        /// Test the property 'LenderName'
        /// </summary>
        [Fact]
        public void LenderNameTest()
        {
            // TODO unit test for the property 'LenderName'
        }
        /// <summary>
        /// Test the property 'BorrowerId'
        /// </summary>
        [Fact]
        public void BorrowerIdTest()
        {
            // TODO unit test for the property 'BorrowerId'
        }
        /// <summary>
        /// Test the property 'BorrowerName'
        /// </summary>
        [Fact]
        public void BorrowerNameTest()
        {
            // TODO unit test for the property 'BorrowerName'
        }
        /// <summary>
        /// Test the property 'CurrentAmount'
        /// </summary>
        [Fact]
        public void CurrentAmountTest()
        {
            // TODO unit test for the property 'CurrentAmount'
        }
        /// <summary>
        /// Test the property 'LoanType'
        /// </summary>
        [Fact]
        public void LoanTypeTest()
        {
            // TODO unit test for the property 'LoanType'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'MaturityDate'
        /// </summary>
        [Fact]
        public void MaturityDateTest()
        {
            // TODO unit test for the property 'MaturityDate'
        }
        /// <summary>
        /// Test the property 'Sweep'
        /// </summary>
        [Fact]
        public void SweepTest()
        {
            // TODO unit test for the property 'Sweep'
        }
        /// <summary>
        /// Test the property 'AutoRepaymentSweep'
        /// </summary>
        [Fact]
        public void AutoRepaymentSweepTest()
        {
            // TODO unit test for the property 'AutoRepaymentSweep'
        }
        /// <summary>
        /// Test the property 'CurrencyISOCode'
        /// </summary>
        [Fact]
        public void CurrencyISOCodeTest()
        {
            // TODO unit test for the property 'CurrencyISOCode'
        }
        /// <summary>
        /// Test the property 'LendingPartnerIds'
        /// </summary>
        [Fact]
        public void LendingPartnerIdsTest()
        {
            // TODO unit test for the property 'LendingPartnerIds'
        }
        /// <summary>
        /// Test the property 'Owners'
        /// </summary>
        [Fact]
        public void OwnersTest()
        {
            // TODO unit test for the property 'Owners'
        }
        /// <summary>
        /// Test the property 'CurrentAmountAtRepay'
        /// </summary>
        [Fact]
        public void CurrentAmountAtRepayTest()
        {
            // TODO unit test for the property 'CurrentAmountAtRepay'
        }
        /// <summary>
        /// Test the property 'CurrentAmountAtDelete'
        /// </summary>
        [Fact]
        public void CurrentAmountAtDeleteTest()
        {
            // TODO unit test for the property 'CurrentAmountAtDelete'
        }
        /// <summary>
        /// Test the property 'CurrentAmountAtWriteOff'
        /// </summary>
        [Fact]
        public void CurrentAmountAtWriteOffTest()
        {
            // TODO unit test for the property 'CurrentAmountAtWriteOff'
        }

    }

}
