/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Loan.Client.Api;
using YL.Web.Api.ThirdParty.Loan.Client.Model;
using YL.Web.Api.ThirdParty.Loan.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Loan.Client.Test
{
    /// <summary>
    ///  Class for testing LoanRepaymentModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoanRepaymentModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoanRepaymentModel
        //private LoanRepaymentModel instance;

        public LoanRepaymentModelTests()
        {
            // TODO uncomment below to create an instance of LoanRepaymentModel
            //instance = new LoanRepaymentModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoanRepaymentModel
        /// </summary>
        [Fact]
        public void LoanRepaymentModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanRepaymentModel
            //Assert.IsInstanceOfType<LoanRepaymentModel> (instance, "variable 'instance' is a LoanRepaymentModel");
        }


        /// <summary>
        /// Test the property 'TransactionHistoryId'
        /// </summary>
        [Fact]
        public void TransactionHistoryIdTest()
        {
            // TODO unit test for the property 'TransactionHistoryId'
        }
        /// <summary>
        /// Test the property 'PaymentDate'
        /// </summary>
        [Fact]
        public void PaymentDateTest()
        {
            // TODO unit test for the property 'PaymentDate'
        }
        /// <summary>
        /// Test the property 'TotalCardTransactions'
        /// </summary>
        [Fact]
        public void TotalCardTransactionsTest()
        {
            // TODO unit test for the property 'TotalCardTransactions'
        }
        /// <summary>
        /// Test the property 'Sweep'
        /// </summary>
        [Fact]
        public void SweepTest()
        {
            // TODO unit test for the property 'Sweep'
        }
        /// <summary>
        /// Test the property 'RepaymentAmount'
        /// </summary>
        [Fact]
        public void RepaymentAmountTest()
        {
            // TODO unit test for the property 'RepaymentAmount'
        }
        /// <summary>
        /// Test the property 'LoanBalance'
        /// </summary>
        [Fact]
        public void LoanBalanceTest()
        {
            // TODO unit test for the property 'LoanBalance'
        }
        /// <summary>
        /// Test the property 'Payments'
        /// </summary>
        [Fact]
        public void PaymentsTest()
        {
            // TODO unit test for the property 'Payments'
        }

    }

}
