/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Loan.Client.Api;
using YL.Web.Api.ThirdParty.Loan.Client.Model;
using YL.Web.Api.ThirdParty.Loan.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Loan.Client.Test
{
    /// <summary>
    ///  Class for testing LoanRefinancingDetailsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoanRefinancingDetailsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoanRefinancingDetailsModel
        //private LoanRefinancingDetailsModel instance;

        public LoanRefinancingDetailsModelTests()
        {
            // TODO uncomment below to create an instance of LoanRefinancingDetailsModel
            //instance = new LoanRefinancingDetailsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoanRefinancingDetailsModel
        /// </summary>
        [Fact]
        public void LoanRefinancingDetailsModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanRefinancingDetailsModel
            //Assert.IsInstanceOfType<LoanRefinancingDetailsModel> (instance, "variable 'instance' is a LoanRefinancingDetailsModel");
        }


        /// <summary>
        /// Test the property 'RefinancingFromLoanDetails'
        /// </summary>
        [Fact]
        public void RefinancingFromLoanDetailsTest()
        {
            // TODO unit test for the property 'RefinancingFromLoanDetails'
        }
        /// <summary>
        /// Test the property 'RefinancingToLoanDetails'
        /// </summary>
        [Fact]
        public void RefinancingToLoanDetailsTest()
        {
            // TODO unit test for the property 'RefinancingToLoanDetails'
        }

    }

}
