/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Loan.Client.Api;
using YL.Web.Api.ThirdParty.Loan.Client.Model;
using YL.Web.Api.ThirdParty.Loan.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Loan.Client.Test
{
    /// <summary>
    ///  Class for testing LoanDocumentModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoanDocumentModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoanDocumentModel
        //private LoanDocumentModel instance;

        public LoanDocumentModelTests()
        {
            // TODO uncomment below to create an instance of LoanDocumentModel
            //instance = new LoanDocumentModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoanDocumentModel
        /// </summary>
        [Fact]
        public void LoanDocumentModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanDocumentModel
            //Assert.IsInstanceOfType<LoanDocumentModel> (instance, "variable 'instance' is a LoanDocumentModel");
        }


        /// <summary>
        /// Test the property 'Document'
        /// </summary>
        [Fact]
        public void DocumentTest()
        {
            // TODO unit test for the property 'Document'
        }
        /// <summary>
        /// Test the property 'DocumentType'
        /// </summary>
        [Fact]
        public void DocumentTypeTest()
        {
            // TODO unit test for the property 'DocumentType'
        }

    }

}
