/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Loan.Client.Api;
using YL.Web.Api.ThirdParty.Loan.Client.Model;
using YL.Web.Api.ThirdParty.Loan.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Loan.Client.Test
{
    /// <summary>
    ///  Class for testing LoanModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoanModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoanModel
        //private LoanModel instance;

        public LoanModelTests()
        {
            // TODO uncomment below to create an instance of LoanModel
            //instance = new LoanModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoanModel
        /// </summary>
        [Fact]
        public void LoanModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanModel
            //Assert.IsInstanceOfType<LoanModel> (instance, "variable 'instance' is a LoanModel");
        }


        /// <summary>
        /// Test the property 'AutoRepaymentSweep'
        /// </summary>
        [Fact]
        public void AutoRepaymentSweepTest()
        {
            // TODO unit test for the property 'AutoRepaymentSweep'
        }
        /// <summary>
        /// Test the property 'BorrowerId'
        /// </summary>
        [Fact]
        public void BorrowerIdTest()
        {
            // TODO unit test for the property 'BorrowerId'
        }
        /// <summary>
        /// Test the property 'BorrowerName'
        /// </summary>
        [Fact]
        public void BorrowerNameTest()
        {
            // TODO unit test for the property 'BorrowerName'
        }
        /// <summary>
        /// Test the property 'CreditRating'
        /// </summary>
        [Fact]
        public void CreditRatingTest()
        {
            // TODO unit test for the property 'CreditRating'
        }
        /// <summary>
        /// Test the property 'CurrencyISOCode'
        /// </summary>
        [Fact]
        public void CurrencyISOCodeTest()
        {
            // TODO unit test for the property 'CurrencyISOCode'
        }
        /// <summary>
        /// Test the property 'CurrentAmount'
        /// </summary>
        [Fact]
        public void CurrentAmountTest()
        {
            // TODO unit test for the property 'CurrentAmount'
        }
        /// <summary>
        /// Test the property 'CurrentServiceChargeRate'
        /// </summary>
        [Fact]
        public void CurrentServiceChargeRateTest()
        {
            // TODO unit test for the property 'CurrentServiceChargeRate'
        }
        /// <summary>
        /// Test the property 'DefaultDetails'
        /// </summary>
        [Fact]
        public void DefaultDetailsTest()
        {
            // TODO unit test for the property 'DefaultDetails'
        }
        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Fact]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LenderId'
        /// </summary>
        [Fact]
        public void LenderIdTest()
        {
            // TODO unit test for the property 'LenderId'
        }
        /// <summary>
        /// Test the property 'LenderName'
        /// </summary>
        [Fact]
        public void LenderNameTest()
        {
            // TODO unit test for the property 'LenderName'
        }
        /// <summary>
        /// Test the property 'MaturityDate'
        /// </summary>
        [Fact]
        public void MaturityDateTest()
        {
            // TODO unit test for the property 'MaturityDate'
        }
        /// <summary>
        /// Test the property 'OriginalAmount'
        /// </summary>
        [Fact]
        public void OriginalAmountTest()
        {
            // TODO unit test for the property 'OriginalAmount'
        }
        /// <summary>
        /// Test the property 'OriginalProjectedAnnualisedReturn'
        /// </summary>
        [Fact]
        public void OriginalProjectedAnnualisedReturnTest()
        {
            // TODO unit test for the property 'OriginalProjectedAnnualisedReturn'
        }
        /// <summary>
        /// Test the property 'OriginalServiceChargeRate'
        /// </summary>
        [Fact]
        public void OriginalServiceChargeRateTest()
        {
            // TODO unit test for the property 'OriginalServiceChargeRate'
        }
        /// <summary>
        /// Test the property 'ProjectedRepaymentDate'
        /// </summary>
        [Fact]
        public void ProjectedRepaymentDateTest()
        {
            // TODO unit test for the property 'ProjectedRepaymentDate'
        }
        /// <summary>
        /// Test the property 'SecurityAndGuarantees'
        /// </summary>
        [Fact]
        public void SecurityAndGuaranteesTest()
        {
            // TODO unit test for the property 'SecurityAndGuarantees'
        }
        /// <summary>
        /// Test the property 'LoanType'
        /// </summary>
        [Fact]
        public void LoanTypeTest()
        {
            // TODO unit test for the property 'LoanType'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Sweep'
        /// </summary>
        [Fact]
        public void SweepTest()
        {
            // TODO unit test for the property 'Sweep'
        }
        /// <summary>
        /// Test the property 'UseOfProceeds'
        /// </summary>
        [Fact]
        public void UseOfProceedsTest()
        {
            // TODO unit test for the property 'UseOfProceeds'
        }
        /// <summary>
        /// Test the property 'LoanNumber'
        /// </summary>
        [Fact]
        public void LoanNumberTest()
        {
            // TODO unit test for the property 'LoanNumber'
        }
        /// <summary>
        /// Test the property 'RefinancingDetails'
        /// </summary>
        [Fact]
        public void RefinancingDetailsTest()
        {
            // TODO unit test for the property 'RefinancingDetails'
        }
        /// <summary>
        /// Test the property 'EarlyRenewalDetails'
        /// </summary>
        [Fact]
        public void EarlyRenewalDetailsTest()
        {
            // TODO unit test for the property 'EarlyRenewalDetails'
        }
        /// <summary>
        /// Test the property 'FundingDetails'
        /// </summary>
        [Fact]
        public void FundingDetailsTest()
        {
            // TODO unit test for the property 'FundingDetails'
        }
        /// <summary>
        /// Test the property 'WriteOffDetails'
        /// </summary>
        [Fact]
        public void WriteOffDetailsTest()
        {
            // TODO unit test for the property 'WriteOffDetails'
        }
        /// <summary>
        /// Test the property 'Owners'
        /// </summary>
        [Fact]
        public void OwnersTest()
        {
            // TODO unit test for the property 'Owners'
        }
        /// <summary>
        /// Test the property 'ThirdPartyReferences'
        /// </summary>
        [Fact]
        public void ThirdPartyReferencesTest()
        {
            // TODO unit test for the property 'ThirdPartyReferences'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Fact]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }

    }

}
