/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Loan.Client.Api;
using YL.Web.Api.ThirdParty.Loan.Client.Model;
using YL.Web.Api.ThirdParty.Loan.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Loan.Client.Test
{
    /// <summary>
    ///  Class for testing LoanOwnerModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoanOwnerModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoanOwnerModel
        //private LoanOwnerModel instance;

        public LoanOwnerModelTests()
        {
            // TODO uncomment below to create an instance of LoanOwnerModel
            //instance = new LoanOwnerModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoanOwnerModel
        /// </summary>
        [Fact]
        public void LoanOwnerModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanOwnerModel
            //Assert.IsInstanceOfType<LoanOwnerModel> (instance, "variable 'instance' is a LoanOwnerModel");
        }


        /// <summary>
        /// Test the property 'OwnerLenderId'
        /// </summary>
        [Fact]
        public void OwnerLenderIdTest()
        {
            // TODO unit test for the property 'OwnerLenderId'
        }
        /// <summary>
        /// Test the property 'OwnerLenderNumber'
        /// </summary>
        [Fact]
        public void OwnerLenderNumberTest()
        {
            // TODO unit test for the property 'OwnerLenderNumber'
        }
        /// <summary>
        /// Test the property 'OwnershipPercentage'
        /// </summary>
        [Fact]
        public void OwnershipPercentageTest()
        {
            // TODO unit test for the property 'OwnershipPercentage'
        }
        /// <summary>
        /// Test the property 'OwnershipPaymentStatus'
        /// </summary>
        [Fact]
        public void OwnershipPaymentStatusTest()
        {
            // TODO unit test for the property 'OwnershipPaymentStatus'
        }
        /// <summary>
        /// Test the property 'OwnershipPaymentAmountPaid'
        /// </summary>
        [Fact]
        public void OwnershipPaymentAmountPaidTest()
        {
            // TODO unit test for the property 'OwnershipPaymentAmountPaid'
        }
        /// <summary>
        /// Test the property 'ExpectedOwnershipPaymentAmount'
        /// </summary>
        [Fact]
        public void ExpectedOwnershipPaymentAmountTest()
        {
            // TODO unit test for the property 'ExpectedOwnershipPaymentAmount'
        }
        /// <summary>
        /// Test the property 'OwnerName'
        /// </summary>
        [Fact]
        public void OwnerNameTest()
        {
            // TODO unit test for the property 'OwnerName'
        }
        /// <summary>
        /// Test the property 'RefinancingRepaymentAmountDue'
        /// </summary>
        [Fact]
        public void RefinancingRepaymentAmountDueTest()
        {
            // TODO unit test for the property 'RefinancingRepaymentAmountDue'
        }
        /// <summary>
        /// Test the property 'TotalRepaymentsReceived'
        /// </summary>
        [Fact]
        public void TotalRepaymentsReceivedTest()
        {
            // TODO unit test for the property 'TotalRepaymentsReceived'
        }
        /// <summary>
        /// Test the property 'TotalRepaymentsOwed'
        /// </summary>
        [Fact]
        public void TotalRepaymentsOwedTest()
        {
            // TODO unit test for the property 'TotalRepaymentsOwed'
        }
        /// <summary>
        /// Test the property 'GeneratedTransferAgreement'
        /// </summary>
        [Fact]
        public void GeneratedTransferAgreementTest()
        {
            // TODO unit test for the property 'GeneratedTransferAgreement'
        }
        /// <summary>
        /// Test the property 'TransferAgreementDocumentSigningId'
        /// </summary>
        [Fact]
        public void TransferAgreementDocumentSigningIdTest()
        {
            // TODO unit test for the property 'TransferAgreementDocumentSigningId'
        }

    }

}
