/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Loan.Client.Api;
using YL.Web.Api.ThirdParty.Loan.Client.Model;
using YL.Web.Api.ThirdParty.Loan.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Loan.Client.Test
{
    /// <summary>
    ///  Class for testing RefinancingLoanDetailsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RefinancingLoanDetailsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RefinancingLoanDetailsModel
        //private RefinancingLoanDetailsModel instance;

        public RefinancingLoanDetailsModelTests()
        {
            // TODO uncomment below to create an instance of RefinancingLoanDetailsModel
            //instance = new RefinancingLoanDetailsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RefinancingLoanDetailsModel
        /// </summary>
        [Fact]
        public void RefinancingLoanDetailsModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RefinancingLoanDetailsModel
            //Assert.IsInstanceOfType<RefinancingLoanDetailsModel> (instance, "variable 'instance' is a RefinancingLoanDetailsModel");
        }


        /// <summary>
        /// Test the property 'LoanId'
        /// </summary>
        [Fact]
        public void LoanIdTest()
        {
            // TODO unit test for the property 'LoanId'
        }
        /// <summary>
        /// Test the property 'LoanNumber'
        /// </summary>
        [Fact]
        public void LoanNumberTest()
        {
            // TODO unit test for the property 'LoanNumber'
        }
        /// <summary>
        /// Test the property 'OldLoanOriginalAmount'
        /// </summary>
        [Fact]
        public void OldLoanOriginalAmountTest()
        {
            // TODO unit test for the property 'OldLoanOriginalAmount'
        }
        /// <summary>
        /// Test the property 'OldLoanFundedAmount'
        /// </summary>
        [Fact]
        public void OldLoanFundedAmountTest()
        {
            // TODO unit test for the property 'OldLoanFundedAmount'
        }
        /// <summary>
        /// Test the property 'OldLoanDiscount'
        /// </summary>
        [Fact]
        public void OldLoanDiscountTest()
        {
            // TODO unit test for the property 'OldLoanDiscount'
        }
        /// <summary>
        /// Test the property 'OldLoanDiscountAmount'
        /// </summary>
        [Fact]
        public void OldLoanDiscountAmountTest()
        {
            // TODO unit test for the property 'OldLoanDiscountAmount'
        }
        /// <summary>
        /// Test the property 'OldLoanRepaymentAmount'
        /// </summary>
        [Fact]
        public void OldLoanRepaymentAmountTest()
        {
            // TODO unit test for the property 'OldLoanRepaymentAmount'
        }
        /// <summary>
        /// Test the property 'OldLoanRepaymentFundedAmount'
        /// </summary>
        [Fact]
        public void OldLoanRepaymentFundedAmountTest()
        {
            // TODO unit test for the property 'OldLoanRepaymentFundedAmount'
        }
        /// <summary>
        /// Test the property 'OldLoanRepaymentDiscountAmount'
        /// </summary>
        [Fact]
        public void OldLoanRepaymentDiscountAmountTest()
        {
            // TODO unit test for the property 'OldLoanRepaymentDiscountAmount'
        }
        /// <summary>
        /// Test the property 'OldLoanUnpaidAmount'
        /// </summary>
        [Fact]
        public void OldLoanUnpaidAmountTest()
        {
            // TODO unit test for the property 'OldLoanUnpaidAmount'
        }
        /// <summary>
        /// Test the property 'OldLoanUnpaidFundedAmount'
        /// </summary>
        [Fact]
        public void OldLoanUnpaidFundedAmountTest()
        {
            // TODO unit test for the property 'OldLoanUnpaidFundedAmount'
        }
        /// <summary>
        /// Test the property 'OldLoanUnpaidDiscountAmount'
        /// </summary>
        [Fact]
        public void OldLoanUnpaidDiscountAmountTest()
        {
            // TODO unit test for the property 'OldLoanUnpaidDiscountAmount'
        }
        /// <summary>
        /// Test the property 'NewLoanIncreaseAmount'
        /// </summary>
        [Fact]
        public void NewLoanIncreaseAmountTest()
        {
            // TODO unit test for the property 'NewLoanIncreaseAmount'
        }
        /// <summary>
        /// Test the property 'NewLoanIncreaseFundedAmount'
        /// </summary>
        [Fact]
        public void NewLoanIncreaseFundedAmountTest()
        {
            // TODO unit test for the property 'NewLoanIncreaseFundedAmount'
        }
        /// <summary>
        /// Test the property 'NewLoanIncreaseDiscount'
        /// </summary>
        [Fact]
        public void NewLoanIncreaseDiscountTest()
        {
            // TODO unit test for the property 'NewLoanIncreaseDiscount'
        }
        /// <summary>
        /// Test the property 'NewLoanIncreaseDiscountAmount'
        /// </summary>
        [Fact]
        public void NewLoanIncreaseDiscountAmountTest()
        {
            // TODO unit test for the property 'NewLoanIncreaseDiscountAmount'
        }
        /// <summary>
        /// Test the property 'ConsolidatedLoanOriginalAmount'
        /// </summary>
        [Fact]
        public void ConsolidatedLoanOriginalAmountTest()
        {
            // TODO unit test for the property 'ConsolidatedLoanOriginalAmount'
        }
        /// <summary>
        /// Test the property 'ConsolidatedLoanFundedAmount'
        /// </summary>
        [Fact]
        public void ConsolidatedLoanFundedAmountTest()
        {
            // TODO unit test for the property 'ConsolidatedLoanFundedAmount'
        }
        /// <summary>
        /// Test the property 'ConsolidatedLoanDiscount'
        /// </summary>
        [Fact]
        public void ConsolidatedLoanDiscountTest()
        {
            // TODO unit test for the property 'ConsolidatedLoanDiscount'
        }
        /// <summary>
        /// Test the property 'ConsolidatedLoanDiscountAmount'
        /// </summary>
        [Fact]
        public void ConsolidatedLoanDiscountAmountTest()
        {
            // TODO unit test for the property 'ConsolidatedLoanDiscountAmount'
        }

    }

}
