/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Loan.Client.Api;
using YL.Web.Api.ThirdParty.Loan.Client.Model;
using YL.Web.Api.ThirdParty.Loan.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Loan.Client.Test
{
    /// <summary>
    ///  Class for testing ThirdPartyReferenceModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ThirdPartyReferenceModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ThirdPartyReferenceModel
        //private ThirdPartyReferenceModel instance;

        public ThirdPartyReferenceModelTests()
        {
            // TODO uncomment below to create an instance of ThirdPartyReferenceModel
            //instance = new ThirdPartyReferenceModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ThirdPartyReferenceModel
        /// </summary>
        [Fact]
        public void ThirdPartyReferenceModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ThirdPartyReferenceModel
            //Assert.IsInstanceOfType<ThirdPartyReferenceModel> (instance, "variable 'instance' is a ThirdPartyReferenceModel");
        }


        /// <summary>
        /// Test the property 'ThirdPartyId'
        /// </summary>
        [Fact]
        public void ThirdPartyIdTest()
        {
            // TODO unit test for the property 'ThirdPartyId'
        }
        /// <summary>
        /// Test the property 'ThirdPartyReference'
        /// </summary>
        [Fact]
        public void ThirdPartyReferenceTest()
        {
            // TODO unit test for the property 'ThirdPartyReference'
        }

    }

}
