/* 
 * Third Party Loan API
 *
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = YL.Web.Api.ThirdParty.Loan.Client.Client.OpenAPIDateConverter;

namespace YL.Web.Api.ThirdParty.Loan.Client.Model
{
    /// <summary>
    /// A model detailing the refinancing of a given loan, if applicable
    /// </summary>
    [DataContract]
    public partial class LoanRefinancingDetailsModel :  IEquatable<LoanRefinancingDetailsModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoanRefinancingDetailsModel" /> class.
        /// </summary>
        /// <param name="refinancingFromLoanDetails">refinancingFromLoanDetails.</param>
        /// <param name="refinancingToLoanDetails">refinancingToLoanDetails.</param>
        public LoanRefinancingDetailsModel(RefinancingLoanDetailsModel refinancingFromLoanDetails = default(RefinancingLoanDetailsModel), RefinancingLoanDetailsModel refinancingToLoanDetails = default(RefinancingLoanDetailsModel))
        {
            this.RefinancingFromLoanDetails = refinancingFromLoanDetails;
            this.RefinancingToLoanDetails = refinancingToLoanDetails;
        }
        
        /// <summary>
        /// Gets or Sets RefinancingFromLoanDetails
        /// </summary>
        [DataMember(Name="refinancingFromLoanDetails", EmitDefaultValue=false)]
        public RefinancingLoanDetailsModel RefinancingFromLoanDetails { get; set; }

        /// <summary>
        /// Gets or Sets RefinancingToLoanDetails
        /// </summary>
        [DataMember(Name="refinancingToLoanDetails", EmitDefaultValue=false)]
        public RefinancingLoanDetailsModel RefinancingToLoanDetails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LoanRefinancingDetailsModel {\n");
            sb.Append("  RefinancingFromLoanDetails: ").Append(RefinancingFromLoanDetails).Append("\n");
            sb.Append("  RefinancingToLoanDetails: ").Append(RefinancingToLoanDetails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LoanRefinancingDetailsModel);
        }

        /// <summary>
        /// Returns true if LoanRefinancingDetailsModel instances are equal
        /// </summary>
        /// <param name="input">Instance of LoanRefinancingDetailsModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LoanRefinancingDetailsModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RefinancingFromLoanDetails == input.RefinancingFromLoanDetails ||
                    (this.RefinancingFromLoanDetails != null &&
                    this.RefinancingFromLoanDetails.Equals(input.RefinancingFromLoanDetails))
                ) && 
                (
                    this.RefinancingToLoanDetails == input.RefinancingToLoanDetails ||
                    (this.RefinancingToLoanDetails != null &&
                    this.RefinancingToLoanDetails.Equals(input.RefinancingToLoanDetails))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RefinancingFromLoanDetails != null)
                    hashCode = hashCode * 59 + this.RefinancingFromLoanDetails.GetHashCode();
                if (this.RefinancingToLoanDetails != null)
                    hashCode = hashCode * 59 + this.RefinancingToLoanDetails.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
